version: "3.8"

services:
  localstack:
    container_name: "cpf-reporter-localstack-main"
    image: localstack/localstack
    ports:
      - "4566:4566"           # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-west-2}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./entrypoint/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
