# Configuration for https://github.com/actions/dependency-review-action
# Used in .github/workflows/code-scanning.yml

fail_on_scopes:
  - runtime

# All allowances should provide details, including rationale.
allow_ghsas:
  # Only used during build / development:
  - GHSA-pfrx-2q88-qq97  # Got allows a redirect to a UNIX socket (moderate severity)
  - GHSA-9c47-m6qq-7p4h  # Prototype Pollution in JSON5 via Parse Method (high severity)
  - GHSA-ww39-953v-wcq6  # glob-parent vulnerable to Regular Expression Denial of Service in enclosure regex (high severity)
  # Last remaining usage of vulnerable semver (7.0.0) is used for dev update notifications:
  - GHSA-c2qf-rxjj-qqgw  # semver vulnerable to Regular Expression Denial of Service (moderate severity)
