nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.7.0.cjs

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - x86
    - arm
    - ia32
  libc:
    - glibc
    - musl
