// This file was generated by RedwoodJS
import * as Cell from './EditAgencyCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditAgencyById, EditAgencyByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditAgencyCell'

type CellInputs = CellProps<SuccessType, EditAgencyById, typeof Cell, EditAgencyByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
