// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/weronika/code/cpf-reporter/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/NotFoundPage/NotFoundPage'
import AgencyAgenciesPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/Agency/AgenciesPage/AgenciesPage'
import AgencyAgencyPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/Agency/AgencyPage/AgencyPage'
import AgencyEditAgencyPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/Agency/EditAgencyPage/EditAgencyPage'
import AgencyNewAgencyPageType from '/Users/weronika/code/cpf-reporter/web/src/pages/Agency/NewAgencyPage/NewAgencyPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const AgencyAgenciesPage: typeof AgencyAgenciesPageType
  const AgencyAgencyPage: typeof AgencyAgencyPageType
  const AgencyEditAgencyPage: typeof AgencyEditAgencyPageType
  const AgencyNewAgencyPage: typeof AgencyNewAgencyPageType
}

//# sourceMappingURL=web-routesPages.d.ts.map
