// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
    newAgency: (params?: RouteParams<"/agencies/new"> & QueryParams) => "/agencies/new"
    editAgency: (params?: RouteParams<"/agencies/{id:Int}/edit"> & QueryParams) => "/agencies/{id:Int}/edit"
    agency: (params?: RouteParams<"/agencies/{id:Int}"> & QueryParams) => "/agencies/{id:Int}"
    agencies: (params?: RouteParams<"/agencies"> & QueryParams) => "/agencies"
  }
}

//# sourceMappingURL=web-routerRoutes.d.ts.map
