// This file was generated by RedwoodJS
import * as Cell from './AgenciesCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindAgencies, FindAgenciesVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './AgenciesCell'

type CellInputs = CellProps<SuccessType, FindAgencies, typeof Cell, FindAgenciesVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
