// This file was generated by RedwoodJS
import * as Cell from './AgenciesCell'
import type { CellProps } from '@redwoodjs/web'
import type { undefined, undefinedVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './AgenciesCell'

type CellInputs = CellProps<SuccessType, undefined, typeof Cell, undefinedVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
