// This file was generated by RedwoodJS
import * as Cell from './AgencyCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindAgencyById, FindAgencyByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './AgencyCell'

type CellInputs = CellProps<SuccessType, FindAgencyById, typeof Cell, FindAgencyByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
