name: Test workflow

on:
  pull_request: {}

permissions:
  contents: read
  packages: write

jobs:
  build-console:
    permissions:
      contents: read
      packages: write
    name: Build RedwoodJS console
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      docker-image-push: true
      docker-image-args-ref: ${{ github.ref }}
      docker-image-tag-latest: false
      docker-image-tag-pr: "${{ github.event.pull_request.number }}"
      docker-image-upload-attestations: true
      docker-image-artifacts-retention-days: 14
      docker-image-version: "rc-pr-${{ github.event.pull_request.number }}"
      build-api-image: false
      build-console-image: true
      build-api-functions: false
      build-web: false
